sudo:
  required

services:
  - docker

language: scala

scala:
    - 2.11.7

jdk:
  - oraclejdk8

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - kai_vasya@mail.ru